// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"battleship/controllers"
	"battleship/db/dao"
	"battleship/events/incoming_events"
	"battleship/events/outgoing_events"
	"battleship/service"
	"battleship/socket"
)

// Injectors from wire.go:

func CreateGameController() controllers.GameController {
	gameService := CreateGameService()
	gameControllerImpl := controllers.NewGameControllerImpl(gameService)
	return gameControllerImpl
}

func CreateUserController() controllers.UserController {
	userService := CreateUserService()
	userControllerImpl := controllers.NewUserController(userService)
	return userControllerImpl
}

func CreateGameService() service.GameService {
	gameDao := CreateGameDao()
	userDao := CreateUserDao()
	gameEventDao := CreateGameEventDao()
	outgoingEventHandler := CreateOutgoingEventHandler()
	gameServiceImpl := service.NewGameServiceImpl(gameDao, userDao, gameEventDao, outgoingEventHandler)
	return gameServiceImpl
}

func CreateUserService() service.UserService {
	userDao := CreateUserDao()
	userServiceImpl := service.NewUserServiceImpl(userDao)
	return userServiceImpl
}

func CreateIncomingEventHandler() incoming_events.IncomingEventHandler {
	gameDao := CreateGameDao()
	incomingEventHandlerImpl := incoming_events.NewIncomingEventHandlerImpl(gameDao)
	return incomingEventHandlerImpl
}

func CreateOutgoingEventHandler() outgoing_events.OutgoingEventHandler {
	outgoingEventHandlerImpl := outgoing_events.NewOutgoingEventHandlerImpl()
	return outgoingEventHandlerImpl
}

func CreateSocketHandler() socket.SocketHandler {
	incomingEventHandler := CreateIncomingEventHandler()
	gameService := CreateGameService()
	socketHandlerImpl := socket.NewSocketHandlerImpl(incomingEventHandler, gameService)
	return socketHandlerImpl
}

func CreateGameDao() dao.GameDao {
	gameDaoImpl := dao.NewGameDaoImpl()
	return gameDaoImpl
}

func CreateUserDao() dao.UserDao {
	userDaoImpl := dao.NewUserDaoImpl()
	return userDaoImpl
}

func CreateGameEventDao() dao.GameEventDao {
	gameEventDaoImpl := dao.NewEventGameDaoImpl()
	return gameEventDaoImpl
}
