definitions:
  dto.BattleError:
    properties:
      error_code:
        type: integer
      error_data:
        additionalProperties:
          type: string
        type: object
      error_message:
        type: string
    type: object
  dto.ChangeTurnRequest:
    properties:
      game_id:
        type: string
      user_id:
        type: string
    type: object
  dto.ChangeTurnResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      ok:
        type: boolean
    type: object
  dto.CreateGameRequest:
    properties:
      move_timeout:
        type: integer
      user_id:
        type: string
    type: object
  dto.CreateUserRequest:
    properties:
      mobile:
        type: string
      name:
        type: string
    type: object
  dto.CreateUserResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      id:
        type: string
      ok:
        type: boolean
    type: object
  dto.ExplodeRequest:
    properties:
      game_id:
        type: string
      index:
        type: integer
      user_id:
        type: string
    type: object
  dto.ExplodeResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      has_ship:
        type: boolean
      ok:
        type: boolean
    type: object
  dto.GameDto:
    properties:
      create_date:
        type: string
      id:
        type: string
      move_timeout_sec:
        type: integer
      other_side_joined:
        type: boolean
      state:
        $ref: '#/definitions/dto.GameState'
        type: object
      status:
        type: string
      user_id:
        type: string
      winner_user:
        type: string
      your_turn:
        type: boolean
    type: object
  dto.GameState:
    properties:
      enemy_ground:
        additionalProperties:
          type: boolean
        type: object
      enemy_revealed_ships:
        additionalProperties:
          type: boolean
        type: object
      own_ground:
        additionalProperties:
          type: boolean
        type: object
      own_ships:
        additionalProperties:
          type: boolean
        type: object
    type: object
  dto.GetGameResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      game:
        $ref: '#/definitions/dto.GameDto'
        type: object
      ok:
        type: boolean
    type: object
  dto.JoinGameRequest:
    properties:
      game_id:
        type: string
      user_id:
        type: string
    type: object
  dto.MoveShipRequest:
    properties:
      game_id:
        type: string
      new_ship_index:
        type: integer
      old_ship_index:
        type: integer
      user_id:
        type: string
    type: object
  dto.MoveShipResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      ok:
        type: boolean
    type: object
  dto.RevealEnemyFieldsRequest:
    properties:
      game_id:
        type: string
      index:
        type: integer
      user_id:
        type: string
    type: object
  dto.RevealEnemyFieldsResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      ok:
        type: boolean
      revealed_ship_indexes:
        items:
          type: integer
        type: array
    type: object
  dto.SubmitShipsLocationsRequest:
    properties:
      game_id:
        type: string
      ships_indexes:
        items:
          type: integer
        type: array
      user_id:
        type: string
    type: object
  dto.SubmitShipsLocationsResponse:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      game_status:
        type: string
      ok:
        type: boolean
      turn:
        type: integer
    type: object
  dto.UserDto:
    properties:
      error:
        $ref: '#/definitions/dto.BattleError'
        type: object
      id:
        type: string
      mobile:
        type: string
      name:
        type: string
      ok:
        type: boolean
    type: object
info:
  contact:
    email: m.allamehamiri@gmail.com
    name: Mahmoud AllamehAmiri
  description: Battleship API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Battleship API
  version: "1.0"
paths:
  /api/v1/game:
    post:
      consumes:
      - application/json
      description: create a new battleship game instance
      parameters:
      - description: Create Game Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateGameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Create Game Response
          schema:
            $ref: '#/definitions/dto.GetGameResponse'
      summary: Create game
      tags:
      - Game
  /api/v1/game/{game_id}:
    get:
      consumes:
      - application/json
      description: Get game info
      parameters:
      - description: Game Id
        in: path
        name: game_id
        required: true
        type: string
      - description: User Id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Get Game Response
          schema:
            $ref: '#/definitions/dto.GetGameResponse'
      summary: Get game
      tags:
      - Game
  /api/v1/game/change-turn:
    post:
      consumes:
      - application/json
      description: Change turn
      parameters:
      - description: Change Turn Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ChangeTurnRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Change Turn Response
          schema:
            $ref: '#/definitions/dto.ChangeTurnResponse'
      summary: Change turn
      tags:
      - Game
  /api/v1/game/explode:
    post:
      consumes:
      - application/json
      description: Explode a slot
      parameters:
      - description: Explode request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExplodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Explode Response
          schema:
            $ref: '#/definitions/dto.ExplodeResponse'
      summary: Explode a slot
      tags:
      - Game
  /api/v1/game/join:
    post:
      consumes:
      - application/json
      description: Join to a battleship game instance
      parameters:
      - description: Join Game Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.JoinGameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Get Game response
          schema:
            $ref: '#/definitions/dto.GetGameResponse'
      summary: Join game
      tags:
      - Game
  /api/v1/game/move-ship:
    post:
      consumes:
      - application/json
      description: Move ship to new location
      parameters:
      - description: Move Ship Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MoveShipRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Move Ship Response
          schema:
            $ref: '#/definitions/dto.MoveShipResponse'
      summary: Move ship
      tags:
      - Game
  /api/v1/game/reveal:
    post:
      consumes:
      - application/json
      description: Reveal enemy fields
      parameters:
      - description: Reveal enemy fields request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RevealEnemyFieldsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Reveal Enemy Fields Response
          schema:
            $ref: '#/definitions/dto.RevealEnemyFieldsResponse'
      summary: Reveal enemy fields
      tags:
      - Game
  /api/v1/game/submit-ships:
    post:
      consumes:
      - application/json
      description: submit ship locations
      parameters:
      - description: Submit ships Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SubmitShipsLocationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Submit Ships Locations Response
          schema:
            $ref: '#/definitions/dto.SubmitShipsLocationsResponse'
      summary: submit ship locations
      tags:
      - Game
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: create a new user
      parameters:
      - description: Create User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Create User Response
          schema:
            $ref: '#/definitions/dto.CreateUserResponse'
      summary: Create user
      tags:
      - User
  /api/v1/user/{user_id}:
    get:
      consumes:
      - application/json
      description: Get user info
      parameters:
      - description: ' '
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: UserDto
          schema:
            $ref: '#/definitions/dto.UserDto'
      summary: Get user
      tags:
      - User
swagger: "2.0"
